-- MySQL Script generated by MySQL Workbench
-- Sat Dec  8 14:25:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema property
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema property
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `property` DEFAULT CHARACTER SET utf8 ;
USE `property` ;

-- -----------------------------------------------------
-- Table `property`.`building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `property`.`building` (
  `buildingId` INT NOT NULL AUTO_INCREMENT,
  `buildingName` VARCHAR(45) NULL,
  PRIMARY KEY (`buildingId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `property`.`floor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `property`.`floor` (
  `floorId` INT NOT NULL AUTO_INCREMENT,
  `floorName` VARCHAR(45) NULL,
  `floorArea` VARCHAR(45) NULL,
  `building_buildingId` INT NOT NULL,
  PRIMARY KEY (`floorId`, `building_buildingId`),
  INDEX `fk_floor_building_idx` (`building_buildingId` ASC) VISIBLE,
  CONSTRAINT `fk_floor_building`
    FOREIGN KEY (`building_buildingId`)
    REFERENCES `property`.`building` (`buildingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `property` ;

-- -----------------------------------------------------
-- Placeholder table for view `property`.`propertyDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `property`.`propertyDetails` (`floorName` INT, `floorArea` INT, `buildingName` INT);

-- -----------------------------------------------------
-- View `property`.`propertyDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `property`.`propertyDetails`;
USE `property`;
CREATE  OR REPLACE VIEW `propertyDetails` AS
    SELECT 
        floorName, floorArea, buildingName
    FROM
        floor,
        building
    WHERE
        floor.building_Id = building.buildingId;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
